apiVersion: v1
kind: Service
metadata:
  name: appointmentnpservice-srv
spec:
  type: NodePort
  selector:
    app: appointmentservice
  ports:
    - name: appointmentservice
      protocol: TCP
      port: 80
      targetPort: 80